### ISSUE TITLE
Comps link after comp import gives object has no attribute 'comp_name'.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#128]
After importing Greda 2019 succesfully as per #123, I then imported Greda 2018 seemingly with success. If I recall correctly I then clicked either of the competitions links, got this error and had to restart the app:

```
flask_dev    | [FLASK] 172.18.0.1 - - [27/Oct/2020 16:31:58] "POST /users/_import_comp_fsdb/ HTTP/1.1" 500 -
flask_dev    | [FLASK] Traceback (most recent call last):
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
flask_dev    | [FLASK]     return self.wsgi_app(environ, start_response)
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
flask_dev    | [FLASK]     response = self.handle_exception(e)
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
flask_dev    | [FLASK]     reraise(exc_type, exc_value, tb)
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
flask_dev    | [FLASK]     raise value
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
flask_dev    | [FLASK]     response = self.full_dispatch_request()
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
flask_dev    | [FLASK]     rv = self.handle_user_exception(e)
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
flask_dev    | [FLASK]     reraise(exc_type, exc_value, tb)
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
flask_dev    | [FLASK]     raise value
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
flask_dev    | [FLASK]     rv = self.dispatch_request()
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
flask_dev    | [FLASK]     return view_func(**req.view_args)
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
flask_dev    | [FLASK]     return func(*args, **kwargs)
flask_dev    | [FLASK]   File "/app/airscore/user/views.py", line 166, in _import_comp_fsdb
flask_dev    | [FLASK]     f = FSDB.read(fsdb_file)
flask_dev    | [FLASK]   File "/app/airscore/core/fsdb.py", line 83, in read
flask_dev    | [FLASK]     pilot = Participant.from_fsdb(pil, from_CIVL=from_CIVL)
flask_dev    | [FLASK]   File "/app/airscore/core/pilot/participant.py", line 134, in from_fsdb
flask_dev    | [FLASK]     live = next(el for el in childs if el.get('name') == 'Live')
flask_dev    | [FLASK] StopIteration
flask_dev    | [FLASK] 172.18.0.1 - - [27/Oct/2020 16:33:37] "POST /users/_import_comp_fsdb/ HTTP/1.1" 200 -
flask_dev    | [FLASK] 172.18.0.1 - - [27/Oct/2020 16:33:37] "GET /users/_get_admin_comps?_=1603816282886 HTTP/1.1" 200 -
flask_dev    | [FLASK] 172.18.0.1 - - [27/Oct/2020 16:34:11] "GET /users/comp_settings_admin/51 HTTP/1.1" 500 -
flask_dev    | [FLASK] Traceback (most recent call last):
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
flask_dev    | [FLASK]     return self.wsgi_app(environ, start_response)
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
flask_dev    | [FLASK]     response = self.handle_exception(e)
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
flask_dev    | [FLASK]     reraise(exc_type, exc_value, tb)
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
flask_dev    | [FLASK]     raise value
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
flask_dev    | [FLASK]     response = self.full_dispatch_request()
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
flask_dev    | [FLASK]     rv = self.handle_user_exception(e)
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
flask_dev    | [FLASK]     reraise(exc_type, exc_value, tb)
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
flask_dev    | [FLASK]     raise value
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
flask_dev    | [FLASK]     rv = self.dispatch_request()
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
flask_dev    | [FLASK]     return view_func(**req.view_args)
flask_dev    | [FLASK]   File "/home/sid/.local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
flask_dev    | [FLASK]     return func(*args, **kwargs)
flask_dev    | [FLASK]   File "/app/airscore/user/views.py", line 201, in comp_settings_admin
flask_dev    | [FLASK]     session['comp_name'] = comp.comp_name
flask_dev    | [FLASK] AttributeError: 'NoneType' object has no attribute 'comp_name'
```

**Comment by biuti** [comment]
Should be fixed (https://github.com/FAI-CIVL/FAI-Airscore/commit/8a223195f5c240f6ac25cdfc4eba0df26a3c30e8)
