### ISSUE TITLE
No haversine module on startup.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#138]
When I set `FAI_sphere: on` the application doesn't start up.

https://github.com/FAI-CIVL/FAI-Airscore/blob/b139c33820e28603c0ea51f86110c07fc9295404/defines.yaml.example#L63-L69

The error is:

```
flask.cli.NoAppException: While importing "autoapp", an ImportError was raised:

Traceback (most recent call last):
File "/home/sid/.local/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
__import__(module_name)
File "/app/autoapp.py", line 3, in <module>
from airscore.app import create_app
File "/app/airscore/app.py", line 7, in <module>
from airscore import commands, public, user, internal
File "/app/airscore/public/__init__.py", line 3, in <module>
from . import views # noqa
File "/app/airscore/public/views.py", line 16, in <module>
from airscore.public.forms import LoginForm, ModifyParticipantForm, ResetPasswordForm, ResetPasswordRequestForm
File "/app/airscore/public/forms.py", line 5, in <module>
from airscore.user.models import User
File "/app/airscore/user/__init__.py", line 3, in <module>
from . import views # noqa
File "/app/airscore/user/views.py", line 8, in <module>
import frontendUtils
File "/app/airscore/core/frontendUtils.py", line 2, in <module>
from route import Turnpoint
File "/app/airscore/core/route.py", line 22, in <module>
from haversine import haversine, Unit
ModuleNotFoundError: No module named 'haversine'
```

**Comment by kuaka** [comment]
You will need to rebuild as we have added a dependancy. These libraries are installed at docker build time.

For example sudo docker-compose -f docker-compose-dev.yml build
