### ISSUE TITLE
Lorenzo De Grandis, NYP after bulk import with track.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#251]
I note that pilot 106, Lorenzo De Grandis, is shown as NYP after bulk import. I checked the zip file I used and his track is there.

```
> pwd
/.../output/2020-09-13
> tree
.
├── Andrea_Theodoli_126.igc
├── Christian_Ciech_105.igc
├── Christian_Pollet_119.igc
├── ERIC_MATHURIN_115.igc
├── Emiel_Jansen_132.igc
├── Jean_louis_FOGLIA_108.igc
├── Joerg_Bajewski_103.igc
├── Johann_Courtain_133.igc
├── Joost_Eertman_107.igc
├── Jurgen_Buchert_131.igc
├── Konrad_Lueders_114.igc
├── Lorenzo_De_Grandis_106.igc
├── Marcello_Ciarlo_109.igc
├── Marco_Laurenzi_113.igc
├── Oliver_Salewski_130.igc
├── Roland_Wo�\210hrle_134.igc
├── Rousselet_Simon_124.igc
├── Sasha_Serebrennikova_123.igc
├── Stepan_Zubashev_129.igc
├── Suan_Selenati_118.igc
├── Tullio_Gervasoni_110.igc
└── Valentino_Bau_104.igc
```

![Screen Shot 2021-04-15 at 2 50 40 PM](https://user-images.githubusercontent.com/633283/114923060-5fd34c00-9dfa-11eb-960a-e241d69ed3e9.png)

**Comment by philderbeast** [comment]
Uploading this pilot's track individually, I get an error:

```
Traceback (most recent call last):
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sid/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sid/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sid/.local/lib/python3.8/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/home/sid/.local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/airscore/user/views.py", line 55, in decorated_view
    return func(*args, **kwargs)
  File "/app/airscore/user/views.py", line 1169, in _upload_track
    resp, error = frontendUtils.process_igc(taskid, parid, tracklog, current_user.username,
  File "/app/airscore/core/frontendUtils.py", line 782, in process_igc
    mytrack, error = import_igc_file(tracklog.filename, task, FlightParsingConfig, check_g_record=check_g_record)
  File "/app/airscore/core/trackUtils.py", line 430, in import_igc_file
    flight = Flight.create_from_file(filename=file, config_class=parsing_config)
  File "/app/airscore/core/igc_lib.py", line 623, in create_from_file
    with abs_filename.open('r', encoding="ISO-8859-1") as flight_file:
  File "/home/sid/.local/lib/python3.8/site-packages/pathlib2/__init__.py", line 1461, in open
    return io.open(
  File "/home/sid/.local/lib/python3.8/site-packages/pathlib2/__init__.py", line 1296, in _opener
    return self._accessor.open(self, flags, mode)
  File "/home/sid/.local/lib/python3.8/site-packages/pathlib2/__init__.py", line 585, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/app/airscore/core/Lorenzo_De_Grandis_106.igc'
```

**Comment by philderbeast** [comment]
I get the same error if I delete the track of a pilot I'd successfully imported bulk and then import individually. I tried pilot 105, Christian Ciech.
