### ISSUE TITLE
Error when publishing or downloading results

### ISSUE THREAD

**Issue by joergewald** [FAI-CIVL/FAI-Airscore#287]
I scored a task, and checked "publish results after scoring", but after the scoring, the public website still states "Not yet scored". If I click on the "Download HTML" button, I get the 500 page, and see this in the log:

[2021-05-25 17:13:23,980] ERROR in app: Exception on /users/_download/task_html/SLT2_T1_20210525_171214.json [GET]

Traceback (most recent call last):

File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app

response = self.full_dispatch_request()

File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request

rv = self.handle_user_exception(e)

File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception

reraise(exc_type, exc_value, tb)

File "/home/sid/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise

raise value

File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request

rv = self.dispatch_request()

File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request

return self.view_functions[rule.endpoint](**req.view_args)

File "/home/sid/.local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view

return func(*args, **kwargs)

File "/app/airscore/user/views.py", line 2053, in _download_file

name, content = frontendUtils.create_task_html(filename)

TypeError: cannot unpack non-iterable NoneType object

**Comment by biuti** [comment]
I was not able to replicate. Could this be linked to https://github.com/FAI-CIVL/FAI-Airscore/issues/288?

**Comment by joergewald** [comment]
> I was not able to replicate. Could this be linked to #288?

Absolutely!
